# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29bcf329cb35795fe79990a90267e39f0d85b3fe43f9ed98949b5a0087dd310e7148e051d1bf1f478271f916d50dd3102dd86cf1714262e8447a653712827bb

test:
  secret_key_base: 721c227fe30e3fc462d8a3377fbcd7ba4bf5c07e2d8328099f641cae50277dd58fdda80bd99034b55d3d1660617c0372c9f894473c4d424326c8097b1566fd4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
